window.GUEST_UI = {
  es: {
    home:'Inicio', apartment:'Departamento', nearby:'Cerca', help:'Ayuda', welcome:'Bienvenido a', choose:'¿En qué departamento te alojas?', chooseBody:'Abre tu guía para consultar los equipos, servicios y lugares cercanos.', change:'Cambiar departamento', equipment:'Cómo usar los equipos', contact:'Contactar al anfitrión', checkout:'Salida', returnHome:'Volver al departamento · Av. Uyuni 919', connect:'Conéctate al Wi-Fi', wifi:'La red y la contraseña están en tu mensaje de llegada. Si no las encuentras, escribe al anfitrión.', needHelp:'¿Necesitas ayuda?', tap:'Toca un tema para ver las instrucciones.', about:'Camas y capacidad', arrival:'Llegada y acceso', parking:'Parqueo', parkingBody:'Solicita al guardia que abra el portón para entrar o salir. El parqueo 7 está incluido sin costo cuando ha sido confirmado para tu reserva.', nearbyTitle:'Lo que necesitas, cerca de ti', nearbyBody:'Comida, servicios y planes en Recoleta y Cochabamba. Consulta horarios, fotos y la ruta actual en Google Maps antes de salir.', categories:'Categorías', filters:{all:'Todos', services:'Servicios y compras', food:'Comer y café', nightlife:'Bares y discotecas', parks:'Parques y paseos', culture:'Cultura y cine'}, viewMaps:'Ver en Maps', findMaps:'Buscar en Maps', source:'Sitio / información', more:'Ver más', less:'Ver menos', illustrative:'Imagen ilustrativa', beforeLeaving:'Antes de salir', checkoutItems:['La salida es hasta las 11:00.','Si necesitas más tiempo, consulta al anfitrión con anticipación.'], noSmoking:'No se permite fumar dentro del departamento.', helpBody:'Para consultas de tu estadía, escríbenos por Airbnb.', airbnbHint:'Abre Airbnb → Viajes → tu reserva → mensajes al anfitrión.', report:'Reportar un problema', emergency:'Emergencias · números para llamar', credits:'Créditos de imágenes', notes:'Las fotos ilustrativas representan una categoría; no muestran el establecimiento.'
  },
  en: {
    home:'Home', apartment:'Apartment', nearby:'Nearby', help:'Help', welcome:'Welcome to', choose:'Which apartment are you staying in?', chooseBody:'Open your guide for equipment, services and nearby places.', change:'Change apartment', equipment:'How to use the equipment', contact:'Contact your host', checkout:'Check-out', returnHome:'Back to the apartment · Av. Uyuni 919', connect:'Connect to Wi-Fi', wifi:'The network name and password are in your arrival message. If you cannot find them, message your host.', needHelp:'Need a hand?', tap:'Tap a topic to see the instructions.', about:'Beds and capacity', arrival:'Arrival and access', parking:'Parking', parkingBody:'Ask the guard to open the gate when entering or leaving. Space 7 is included at no extra cost when confirmed for your booking.', nearbyTitle:'Everyday essentials and local discoveries', nearbyBody:'Food, services and things to do in Recoleta and Cochabamba. Check opening hours, photos and the current route in Google Maps before leaving.', categories:'Categories', filters:{all:'All', services:'Services & shopping', food:'Food & coffee', nightlife:'Bars & clubs', parks:'Parks & walks', culture:'Culture & cinema'}, viewMaps:'View in Maps', findMaps:'Search in Maps', source:'Website / information', more:'Show more', less:'Show less', illustrative:'Illustrative photo', beforeLeaving:'Before you leave', checkoutItems:['Check-out is by 11:00 a.m.','If you need more time, ask your host in advance.'], noSmoking:'Smoking is not allowed inside the apartment.', helpBody:'For questions during your stay, message us through Airbnb.', airbnbHint:'Open Airbnb → Trips → your reservation → message your host.', report:'Report a problem', emergency:'Emergencies · tap to call', credits:'Photo credits', notes:'Illustrative photos represent a category, not the actual venue.'
  },
  fr: {
    home:'Accueil', apartment:'Appartement', nearby:'À proximité', help:'Aide', welcome:'Bienvenue à', choose:'Dans quel appartement séjournez-vous ?', chooseBody:'Ouvrez votre guide des équipements, services et adresses à proximité.', change:'Changer d’appartement', equipment:'Utiliser les équipements', contact:'Contacter votre hôte', checkout:'Départ', returnHome:'Retour à l’appartement · Av. Uyuni 919', connect:'Connexion au Wi-Fi', wifi:'Le nom du réseau et le mot de passe figurent dans votre message d’arrivée. Si vous ne les trouvez pas, écrivez à votre hôte.', needHelp:'Besoin d’aide ?', tap:'Touchez un sujet pour afficher les instructions.', about:'Couchages et capacité', arrival:'Arrivée et accès', parking:'Stationnement', parkingBody:'Demandez au gardien d’ouvrir le portail pour entrer ou sortir. La place 7 est incluse sans supplément lorsqu’elle a été confirmée pour votre réservation.', nearbyTitle:'Services pratiques et découvertes locales', nearbyBody:'Restaurants, services et sorties à Recoleta et Cochabamba. Consultez horaires, photos et itinéraire dans Google Maps avant de partir.', categories:'Catégories', filters:{all:'Tous', services:'Services et commerces', food:'Restaurants et cafés', nightlife:'Bars et discothèques', parks:'Parcs et promenades', culture:'Culture et cinéma'}, viewMaps:'Voir dans Maps', findMaps:'Chercher dans Maps', source:'Site / informations', more:'Voir plus', less:'Voir moins', illustrative:'Photo illustrative', beforeLeaving:'Avant votre départ', checkoutItems:['Le départ est prévu au plus tard à 11 h.','Si vous avez besoin de plus de temps, contactez votre hôte à l’avance.'], noSmoking:'Il est interdit de fumer dans l’appartement.', helpBody:'Pour toute question pendant votre séjour, écrivez-nous via Airbnb.', airbnbHint:'Ouvrez Airbnb → Voyages → votre réservation → contacter l’hôte.', report:'Signaler un problème', emergency:'Urgences · appeler', credits:'Crédits photos', notes:'Les photos illustratives représentent une catégorie, pas l’établissement.'
  }
};
