// Factual locations are separate from live category searches. No stored opening hours or ratings.
window.GUEST_PLACES = [
  {name:'FarmaElías · Recoleta',category:'services',query:'FarmaElias Recoleta Beni Rotonda Recoleta Cochabamba',source:'https://farmaelias.com/contactanos/',description:{es:'Farmacia en la calle Beni, esquina rotonda Recoleta. Consulta disponibilidad y horario con la sucursal.',en:'Pharmacy on Beni Street at the Recoleta roundabout. Check availability and hours with the branch.',fr:'Pharmacie rue Beni, à l’angle du rond-point Recoleta. Vérifiez les disponibilités et horaires auprès de la pharmacie.'}},
  {name:'Hipermaxi · Torres Sofer',category:'services',query:'Hipermaxi Torres Sofer Avenida Oquendo 630 Cochabamba',source:'https://www.hipermaxi.com/sucursales',description:{es:'Supermercado sobre la avenida Oquendo, en Torres Sofer, para alimentos y compras de la estadía.',en:'Supermarket on Avenida Oquendo in Torres Sofer, for groceries and everyday supplies.',fr:'Supermarché avenue Oquendo, à Torres Sofer, pour vos courses du séjour.'}},
  {name:'Casa de Campo',category:'food',query:'Casa de Campo Boulevard Recoleta Cochabamba Bolivia',source:'https://casadecampobolivia.com/',description:{es:'Cocina boliviana en el Boulevard Recoleta.',en:'Bolivian food on Boulevard Recoleta.',fr:'Cuisine bolivienne sur le Boulevard Recoleta.'}},
  {name:{es:'Cafés y desayunos',en:'Coffee and breakfast',fr:'Cafés et petits-déjeuners'},category:'food',photo:'coffee',search:true,query:'cafeterias desayunos cerca de Sky Recoleta Avenida Uyuni 919 Cochabamba',description:{es:'Explora cafeterías de la zona en Maps y elige según el menú y el horario del día.',en:'Browse local cafés in Maps and choose by menu and today’s opening hours.',fr:'Découvrez les cafés du quartier dans Maps selon leur menu et les horaires du jour.'}},
  {name:'Boulevard Recoleta',category:'parks',photo:'boulevard',query:'Boulevard Recoleta Cochabamba',description:{es:'Un paseo por Recoleta, con opciones para comer y tomar algo.',en:'A walk through Recoleta with places to eat and have a drink.',fr:'Une promenade dans Recoleta, avec des adresses pour manger ou prendre un verre.'}},
  {name:'Muela del Diablo',category:'nightlife',query:'Muela del Diablo Avenida Potosi 1163 Cochabamba',source:'https://linktr.ee/mueladeldiablocbba',description:{es:'Bar y restaurante en avenida Potosí 1163. Consulta su programación de música y eventos.',en:'Bar and restaurant at Avenida Potosí 1163. Check its music and events schedule.',fr:'Bar-restaurant avenue Potosí 1163. Consultez sa programmation musicale et ses événements.'}},
  {name:'La Estancia',category:'food',query:'La Estancia Boulevard Recoleta Cochabamba',description:{es:'Parrilla en la zona del Boulevard Recoleta. Consulta menú y reservas.',en:'Grill restaurant in the Boulevard Recoleta area. Check the menu and reservations.',fr:'Restaurant de grillades dans le quartier du Boulevard Recoleta. Consultez le menu et les réservations.'}},
  {name:'Las Moras Parrilla',category:'food',query:'Las Moras Parrilla Cochabamba',description:{es:'Otra opción de parrilla en Cochabamba; revisa en Maps la ruta desde el departamento.',en:'Another grill option in Cochabamba; check the route from the apartment in Maps.',fr:'Une autre option de grillades à Cochabamba ; consultez l’itinéraire depuis l’appartement dans Maps.'}},
  {name:'AWRA',category:'nightlife',query:'AWRA Melchor Urquidi Zenon Salinas Cochabamba',source:'https://www.bars10.com/BO/Cochabamba/314798995896596/AWRA',description:{es:'Discoteca en Melchor Urquidi esquina Zenón Salinas. Confirma evento, ingreso y disponibilidad antes de ir.',en:'Nightclub at Melchor Urquidi and Zenón Salinas. Confirm the event, entry requirements and availability before going.',fr:'Discothèque à l’angle Melchor Urquidi et Zenón Salinas. Vérifiez la soirée, les conditions d’entrée et les disponibilités.'}},
  {name:'Jardín Botánico Martín Cárdenas',category:'parks',photo:'garden',query:'Jardin Botanico Martin Cardenas Avenida General Galindo Cochabamba',source:'https://abi.bo/inauguran-un-centro-de-educacion-ambiental-en-cochabamba/',description:{es:'Jardín botánico en la zona de Muyurina para conocer plantas y recorrer sus senderos.',en:'Botanical garden in the Muyurina area for discovering plants and walking its paths.',fr:'Jardin botanique dans le quartier de Muyurina pour découvrir les plantes et parcourir ses sentiers.'}},
  {name:'Parque de la Familia',category:'parks',photo:'family',query:'Parque de la Familia Avenida Costanera Cochabamba',source:'https://sites.google.com/view/cochabambaturistica/parques',description:{es:'Parque de la avenida Costanera, conocido por sus fuentes. Comprueba horarios de acceso y espectáculos.',en:'Park on Avenida Costanera known for its fountains. Check entry and show times.',fr:'Parc avenue Costanera connu pour ses fontaines. Vérifiez les horaires d’accès et des spectacles.'}},
  {name:'Palacio Portales',category:'culture',photo:'palace',query:'Palacio Portales Cochabamba',source:'https://patino.org/es/lugares/palacio-portales/',description:{es:'Arquitectura, jardines y actividades culturales. Consulta visitas y horarios antes de salir.',en:'Architecture, gardens and cultural activities. Check tours and hours before leaving.',fr:'Architecture, jardins et activités culturelles. Consultez les visites et horaires avant de partir.'}},
  {name:'Hupermall · Prime Cinemas',category:'services',query:'Prime Cinemas Hupermall Pando Portales Cochabamba',source:'https://www.baneco.com.bo/tarjeta-de-credito-detalles/96',description:{es:'Compras, comida y cine. Consulta la cartelera y el horario de cada local.',en:'Shopping, food and cinema. Check film listings and individual store hours.',fr:'Commerces, restauration et cinéma. Consultez les séances et les horaires de chaque établissement.'}},
  {name:{es:'Cajeros automáticos',en:'ATMs',fr:'Distributeurs de billets'},category:'services',search:true,query:'cajeros automaticos cerca de Sky Recoleta Avenida Uyuni 919 Cochabamba',description:{es:'Busca un cajero cercano y comprueba en Maps el banco y las condiciones de acceso.',en:'Find a nearby ATM and check the bank and access details in Maps.',fr:'Trouvez un distributeur proche et vérifiez la banque et les conditions d’accès dans Maps.'}},
  {name:{es:'Lavanderías',en:'Laundry services',fr:'Pressings et blanchisseries'},category:'services',search:true,query:'lavanderias cerca de Sky Recoleta Avenida Uyuni 919 Cochabamba',description:{es:'Consulta servicios de lavado, ubicación y contacto. Confirma plazo de entrega y precio.',en:'Find laundry services, locations and contacts. Confirm turnaround time and pricing.',fr:'Trouvez un service de lavage et ses coordonnées. Confirmez le délai et le prix.'}}
];
window.PLACE_PHOTOS = {
  services:{url:'images/services.jpg',real:false},
  coffee:{url:'images/coffee.jpg',real:false},
  nightlife:{url:'images/nightlife.jpg',real:false},
  palace:{url:'images/palace.jpg',real:true},
  family:{url:'images/family.jpg',real:true},
  garden:{url:'images/garden.jpg',real:true},
  boulevard:{url:'images/boulevard.jpg',real:true},
  food:{url:'images/food.jpg',real:false}
};
